// src/assets/counties.ts

export interface County {
  name: string;
  fee: number;
}

export const counties: County[] = [
  { name: "Baringo", fee: 300 },
  { name: "Bomet", fee: 300 },
  { name: "Bungoma", fee: 350 },
  { name: "Busia", fee: 350 },
  { name: "Elgeyo-Marakwet", fee: 350 },
  { name: "Embu", fee: 250 },
  { name: "Garissa", fee: 400 },
  { name: "Homa Bay", fee: 350 },
  { name: "Isiolo", fee: 400 },
  { name: "Kajiado", fee: 200 },
  { name: "Kakamega", fee: 350 },
  { name: "Kericho", fee: 300 },
  { name: "Kiambu", fee: 200 },
  { name: "Kilifi", fee: 450 },
  { name: "Kirinyaga", fee: 250 },
  { name: "Kisii", fee: 300 },
  { name: "Kisumu", fee: 350 },
  { name: "Kitui", fee: 300 },
  { name: "Kwale", fee: 450 },
  { name: "Laikipia", fee: 300 },
  { name: "Lamu", fee: 500 },
  { name: "Machakos", fee: 250 },
  { name: "Makueni", fee: 300 },
  { name: "Mandera", fee: 600 },
  { name: "Marsabit", fee: 500 },
  { name: "Meru", fee: 300 },
  { name: "Migori", fee: 350 },
  { name: "Mombasa", fee: 450 },
  { name: "Murang'a", fee: 250 },
  { name: "Nairobi", fee: 150 },
  { name: "Nakuru", fee: 300 },
  { name: "Nandi", fee: 350 },
  { name: "Narok", fee: 300 },
  { name: "Nyamira", fee: 300 },
  { name: "Nyandarua", fee: 300 },
  { name: "Nyeri", fee: 250 },
  { name: "Samburu", fee: 500 },
  { name: "Siaya", fee: 350 },
  { name: "Taita-Taveta", fee: 400 },
  { name: "Tana River", fee: 500 },
  { name: "Tharaka-Nithi", fee: 300 },
  { name: "Trans Nzoia", fee: 350 },
  { name: "Turkana", fee: 600 },
  { name: "Uasin Gishu", fee: 350 },
  { name: "Vihiga", fee: 350 },
  { name: "Wajir", fee: 600 },
  { name: "West Pokot", fee: 400 },
];
